export {
  authenticationDependencyTokens,
  type AccessTokenService,
  type AccountAuthenticationRepository,
  type AuthenticateWithEmailAndPasswordInput,
  type AuthenticatedAccount,
  type AuthenticationAccountRecord,
  type AuthenticationAudit,
  type AuthenticationClock,
  type AuthenticationEventLogger,
  type AuthenticationSessionIdGenerator,
  type CredentialAuthenticationUseCase,
  type IssueAccessTokenInput,
  type IssuedAccessToken,
  type LoginAuthenticationUseCase,
  type LoginRateLimitConsumption,
  type LoginRateLimitCounter,
  type LoginRateLimitIncrement,
  type LoginRateLimiter,
  type LoginWithEmailAndPasswordResult,
  type PasswordHashService,
  type RecordSuccessfulLoginInput,
  type VerifiedAccessToken,
} from './authentication/index.js';
